version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/apache-tomcat-9.0.1/webapps/profiles
permissions:
   - object: /usr/share/apache-tomcat-9.0.1/webapps/profiles
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/startapache.sh
      runas: root
   AfterInstall:
    - location: scripts/restartapache.sh
      runas: root